{
 "title": "git code base",
 "time": { "from": "2020-12-11T08:00:00.000Z", "to": "2020-12-21T07:59:59.000Z" },
 "panels": [
  {
   "title": "Head Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  COUNT(DISTINCT(member_name)) as value\nFROM daily_status \nWHERE team=\"alpha\""
    }
   ]
  },
  {
   "title": "Member Daily Code Changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  the_date AS \"time\",\n  scrum_members.member_name AS metric,\n  lines_added + lines_removed\nFROM git_daily_status\n  INNER JOIN scrum_members ON git_daily_status.member_name = scrum_members.id\nWHERE\n  $__timeFilter(the_date) and git_daily_status.team = 1\nORDER BY the_date"
    }
   ]
  },
  {
   "title": "Team Daily Code Changes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  the_date AS \"time\",\n  sum(lines_added+lines_removed)\nFROM git_daily_status\nWHERE\n  team = 1 and $__timeFilter(the_date)\nGROUP BY the_date\nORDER BY the_date"
    }
   ]
  },
  {
   "title": "Aggregated Member Removed Code Lines",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  SUM(lines_removed) As \"value\",\n  CAST(scrum_members.member_name as CHAR) as metric\nFROM git_daily_status\n  INNER JOIN scrum_members ON git_daily_status.member_name = scrum_members.id\nWHERE\n  $__timeFilter(the_date) and git_daily_status.team=1\nGROUP BY git_daily_status.member_name"
    }
   ]
  },
  {
   "title": "Aggregated Member New Code Lines",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  SUM(lines_added) As \"value\",\n  CAST(scrum_members.member_name as CHAR) as metric\nFROM git_daily_status\n  INNER JOIN scrum_members ON git_daily_status.member_name = scrum_members.id\nWHERE\n  $__timeFilter(the_date) and git_daily_status.team=1\nGROUP BY git_daily_status.member_name"
    }
   ]
  },
  {
   "title": "Aggregated Team",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as \"time\",\n  SUM(lines_added) as \"Total Lines Added\",\n  SUM(lines_removed) as \"Total Lines Removed\"\nFROM git_daily_status\nWHERE team=1 and $__timeFilter(the_date)\nGROUP BY team\n"
    }
   ]
  }
 ]
}