platform :ios, '10.0'
use_frameworks!

target 'Weather' do
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 5.0.0-beta.5'
    pod 'ReSwift'
    pod 'PromiseKit', '~> 6.8'

    target 'WeatherTests' do
        pod 'SwiftyJSON', '~> 4.0'
        pod 'ReSwift'
        pod 'PromiseKit', '~> 6.8'
    end
end
